# Generated by Django 6.0.5 on 2026-05-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('item_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold_quantity', models.FloatField(default=0)),
                ('total_sales_value', models.FloatField(default=0)),
                ('total_purchased_quantity', models.FloatField(default=0)),
                ('total_purchase_value', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('is_deadstock', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.item')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.FloatField()),
                ('purchase_value', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.FloatField()),
                ('sales_value', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.item')),
            ],
        ),
    ]
