# Generated by Django 6.0.5 on 2026-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_value',
            field=models.FloatField(default=0),
        ),
    ]
